apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:aba44aa8513fab0cd5095eddccfcf9cccdd13177767db30039fcc21358abde91
  name: shaozhendemoregistry.azurecr.io/mobb/hello-openshift:latest
  newName: shaozhendemoregistry.azurecr.io/mobb/hello-openshift:0.1.5-build.15
- digest: sha256:bcdab4d70a67b36a0671025e4484fd350504b1bc65d8da06c31cd03fda4de8f5
  name: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:latest
  newName: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:0.1.5-build.16
