apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:e16a684ba34fbf5688204d727bfba1ddb4a8546376b98ddc218c2de8bbaf4d15
  name: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:latest
  newName: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:0.1.5-build.20
