apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:099943229c317677ddbd8d93444aa95cd115e84e4caa91e164d0ef17fbf7c1e5
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.3-build.6
