apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:ad34061fef23f182ac606cbe6cff6d544c9065f4ebf9b514bef122601970fb2c
  name: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:latest
  newName: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:0.1.5-build.19
