apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:7272b73a514c4b8f8680a7a6c2d0504a9c06d9eeabde29cd1d0a3ad9e443354c
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.4-build.2
