apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:139ac1dcee9fe4cecbbb17b7ba517f2c183980f494ab5e519a7e965cabda7499
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.8-build.1
