apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:a5a1f1ffde4a7b6362538ed73f5e4dd8b575fb744d0a9a45d6ec25f9f8d5304a
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.0-alpha.2
