apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:7a2aee25e65636e66a0854960f891142df1420613dd13e33b79e40acf1f4fc40
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.2.0-alpha.3
