apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:57596ccab781e8caad39629d53ef9f67c31ed69503a16247165ad4b1587f8f69
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.0-alpha.7
