apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:bcb3b3bcf8f44f5ec3b8336ec679bb0f4cccc0c2bd746a150aa600b86bd0cdbc
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.5-build.10
