apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:60a19e8dfed468ac4a11a8a7781a62037f96c0859ef303164c6eddecd158ace9
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.5-build.1
