apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:aba44aa8513fab0cd5095eddccfcf9cccdd13177767db30039fcc21358abde91
  name: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:latest
  newName: shaozhendemoregistry.azurecr.io/mobb/openshift-hellp:0.1.5-build.15
