apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:149f93cf61ed486301844dfe8dd2da3e65012d50a8477f7992916dcf6dd0d9cd
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.5-build.9
