apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:e12f4f4c1acb0bbd1cea4fad9e7271d41e12af8c19c4dd8dc2fd8bb544097a6d
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.7-build.2
