apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:6c139cd3112e6e0a843aee4170cf8beab464c5e435fec5e44abef0017be168bb
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.5-build.12
