apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:70ff7c532c55c512c2825b0ab8b491d0bd482f054c615498f8c4681dcdda8184
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.3-build.5
