apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:40c91e5440b7df8c6a3d659a0128103145e274245d7b3aaf960b9d215a53b823
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.4-build.3
