apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:928d738d1af58e0f216c9e81b9bf74cc0a953dd1ce17250d5d3af9765f1c9c3a
  name: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:latest
  newName: shaozhendemoregistry.azurecr.io/mobb/openshift-hello:0.1.5-build.21
