apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:21d77e22bce5e8dc16e1c67979c41340a042f6349e9905161f4e552a014d7fc2
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.3-build.7
