apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:78f2e578430c64ad952b6d3a7af78490edadc48b14e8ef5705334f905015182c
  name: quay.io/mobb/openshift-hello:latest
  newName: quay.io/mobb/openshift-hello:0.1.4
